import 'package:digifurniture/common/config/theme/theme_export.dart';
import 'package:easy_localization/easy_localization.dart';

final appStringController =
    ChangeNotifierProvider<AppString>((ref) => AppString());

class AppString extends ChangeNotifier {
  String keyIntro1Title = "keyIntro1Title".tr();
  String keyIntro1Desc = "keyIntro1Desc".tr();
  String keyIntro2Title = "keyIntro2Title".tr();
  String keyIntro2Desc = "keyIntro2Desc".tr();
  String keyIntro3Title = "keyIntro3Title".tr();
  String keyIntro3Desc = "keyIntro3Desc".tr();
  String keyNext = "keyNext".tr();
  String keySignIn = "keySignIn".tr();
  String keySignup = "keySignup".tr();
  String keyWelcomeBack = "keyWelcomeBack".tr();
  String keySignInTitle = "keySignInTitle".tr();
  String keyDontHaveAnAccount = "keyDon'tHaveAnAccount?".tr();
  String keyEmailAddress = "keyEmailAddress".tr();
  String keyPassword = "keyPassword".tr();
  String keyRememberMe = "keyRememberMe".tr();
  String keyForgetPassword = "keyForgetPassword?".tr();
  String keySignUpTitle = "keySignUpTitle".tr();
  String keySignUpDesc = "keySignUpDesc".tr();
  String keyDoYouHaveAnyAccount = "keyDoYouHaveAnyAccount?".tr();
  String keyIAgreeWithThe = "keyIAgreeWithThe".tr();
  String keyTermsOfService = "keyTermsOfService".tr();
  String keyPrivacyPolicy = "keyPrivacyPolicy".tr();
  String keyPasswordRecovery = "keyPasswordRecovery".tr();
  String keyPasswordRecoveryDesc = "keyPasswordRecoveryDesc".tr();
  String keyVerificationCode = "keyVerificationCode".tr();
  String keyVerificationCodeSentDesc = "keyVerificationCodeSentDesc".tr();
  String keyChangeYourEmail = "keyChangeYourEmail".tr();
  String keyResend = "keyResend".tr();
  String keyConfirm = "keyConfirm".tr();
  String keySetNewPassword = "keySetNewPassword".tr();
  String keySetNewPasswordDesc = "keySetNewPasswordDesc".tr();
  String keyEnterNewPassword = "keyEnterNewPassword".tr();
  String keyConfirmPassword = "keyConfirmPassword".tr();
  String keyChangePassword = "keyChangePassword".tr();
  String keyPasswordChanged = "keyPasswordChanged".tr();
  String keyPasswordChangedGreetingDesc = "keyPasswordChangedGreetingDesc".tr();
  String keyBackToLogin = "keyBackToLogin".tr();
  String keyOtpVerification = "keyOtpVerification".tr();
  String keyWhoohooo = "keyWhoohooo".tr();
  String keyYourEmailHasBeenVerifiedSuccessfully =
      "keyYourEmailHasBeenVerifiedSuccessfully".tr();
  String keyGoToShopping = "keyGoToShopping".tr();
  String keyUploadImage = "keyUploadImage".tr();
  String keyContinue = "keyContinue".tr();
  String keyFullName = "keyFullName".tr();
  String keyDateOfBirth = "keyDateOfBirth".tr();
  String keyPhoneNumber = "keyPhoneNumber".tr();
  String keyHome = "keyHome".tr();
  String keyProduct = "keyProduct".tr();
  String keyCart = "keyCart".tr();
  String keyOrder = "keyOrder".tr();
  String keyProfile = "keyProfile".tr();
  String keySpecialOffers = "keySpecialOffers".tr();
  String keySeeAll = "keySeeAll".tr();
  String keyMostPopular = "keyMostPopular".tr();
  String keyOff = "keyOff".tr();
  String keyTopCategories = "keyTopCategories".tr();
  String keyNewArrival = "keyNewArrival".tr();
  String keySofa = "keySofa's".tr();
  String keyChair = "keyChair's".tr();
  String keyShareApp = "keyShareApp".tr();
  String keyConfirmToLogOut = "keyConfirmToLogOut".tr();
  String keyCancel = "keyCancel".tr();
  String keyLogout = "keyLogout".tr();
  String keySkip = "keySkip".tr();
  String keySearch = "keySearch".tr();
  String keyMyWishlist = "keyMyWishlist".tr();
  String keyAddToCart = "keyAddToCart".tr();
  String keyProducts = "keyProducts".tr();
  String keyNotification = "keyNotification".tr();
  String keySortAndFilter = "keySortAndFilter".tr();
  String keyCategories = "keyCategories".tr();
  String keyPriceRange = "keyPriceRange".tr();
  String keySortBy = "keySortBy".tr();
  String keyRating = "keyRating".tr();
  String keyApply = "keyApply".tr();
  String keyReset = "keyReset".tr();
  String keyReviews = "keyReviews".tr();

  updateString() {
    keyIntro1Title = "keyIntro1Title".tr();
    keyIntro1Desc = "keyIntro1Desc".tr();
    keyIntro2Title = "keyIntro2Title".tr();
    keyIntro2Desc = "keyIntro2Desc".tr();
    keyIntro3Title = "keyIntro3Title".tr();
    keyIntro3Desc = "keyIntro3Desc".tr();
    keyNext = "keyNext".tr();
    keySignIn = "keySignIn".tr();
    keySignup = "keySignup".tr();
    keyWelcomeBack = "keyWelcomeBack".tr();
    keySignInTitle = "keySignInTitle".tr();
    keyDontHaveAnAccount = "keyDon'tHaveAnAccount?".tr();
    keyEmailAddress = "keyEmailAddress".tr();
    keyPassword = "keyPassword".tr();
    keyRememberMe = "keyRememberMe".tr();
    keyForgetPassword = "keyForgetPassword?".tr();
    keySignUpTitle = "keySignUpTitle".tr();
    keySignUpDesc = "keySignUpDesc".tr();
    keyDoYouHaveAnyAccount = "keyDoYouHaveAnyAccount?".tr();
    keyIAgreeWithThe = "keyIAgreeWithThe".tr();
    keyTermsOfService = "keyTermsOfService".tr();
    keyPrivacyPolicy = "keyPrivacyPolicy".tr();
    keyPasswordRecovery = "keyPasswordRecovery".tr();
    keyPasswordRecoveryDesc = "keyPasswordRecoveryDesc".tr();
    keyVerificationCode = "keyVerificationCode".tr();
    keyVerificationCodeSentDesc = "keyVerificationCodeSentDesc".tr();
    keyChangeYourEmail = "keyChangeYourEmail".tr();
    keyResend = "keyResend".tr();
    keyConfirm = "keyConfirm".tr();
    keySetNewPassword = "keySetNewPassword".tr();
    keySetNewPasswordDesc = "keySetNewPasswordDesc".tr();
    keyEnterNewPassword = "keyEnterNewPassword".tr();
    keyConfirmPassword = "keyConfirmPassword".tr();
    keyChangePassword = "keyChangePassword".tr();
    keyPasswordChanged = "keyPasswordChanged".tr();
    keyPasswordChangedGreetingDesc = "keyPasswordChangedGreetingDesc".tr();
    keyBackToLogin = "keyBackToLogin".tr();
    keyOtpVerification = "keyOtpVerification".tr();
    keyWhoohooo = "keyWhoohooo".tr();
    keyYourEmailHasBeenVerifiedSuccessfully =
        "keyYourEmailHasBeenVerifiedSuccessfully".tr();
    keyGoToShopping = "keyGoToShopping".tr();
    keyUploadImage = "keyUploadImage".tr();
    keyContinue = "keyContinue".tr();
    keyFullName = "keyFullName".tr();
    keyDateOfBirth = "keyDateOfBirth".tr();
    keyPhoneNumber = "keyPhoneNumber".tr();
    keyHome = "keyHome".tr();
    keyProduct = "keyProduct".tr();
    keyCart = "keyCart".tr();
    keyOrder = "keyOrder".tr();
    keyProfile = "keyProfile".tr();
    keySpecialOffers = "keySpecialOffers".tr();
    keySeeAll = "keySeeAll".tr();
    keyMostPopular = "keyMostPopular".tr();
    keyOff = "keyOff".tr();
    keyTopCategories = "keyTopCategories".tr();
    keyNewArrival = "keyNewArrival".tr();
    keySofa = "keySofa's".tr();
    keyChair = "keyChair's".tr();
    keyShareApp = "keyShareApp".tr();
    keyConfirmToLogOut = "keyConfirmToLogOut".tr();
    keyCancel = "keyCancel".tr();
    keyLogout = "keyLogout".tr();
    keySkip = "keySkip".tr();
    keySearch = "keySearch".tr();
    keyMyWishlist = "keyMyWishlist".tr();
    keyAddToCart = "keyAddToCart".tr();
    keyProducts = "keyProducts".tr();
    keyNotification = "keyNotification".tr();
    keySortAndFilter = "keySortAndFilter".tr();
    keyCategories = "keyCategories".tr();
    keyPriceRange = "keyPriceRange".tr();
    keySortBy = "keySortBy".tr();
    keyRating = "keyRating".tr();
    keyApply = "keyApply".tr();
    keyReset = "keyReset".tr();
    keyReviews = "keyReviews".tr();
  }

  updateLanguage(BuildContext context) async {
    if (context.locale == const Locale('en')) {
      await context.setLocale(const Locale('gu'));
    } else {
      await context.setLocale(const Locale('en'));
    }
    updateString();
    notifyListeners();
  }
}
